<?php
require_once('admin/admin_functions.php');
require_once('client/client_functions.php');
require_once('frontend/frontend_functions.php');
require_once('general/general_functions.php');
require_once('teams/team_functions.php');
require_once('messaging/messaging_functions.php');
require_once('invoice/invoice_functions.php');
require_once('quote/quote_functions.php');
require_once('project/project_functions.php');
require_once('task/task_functions.php');
require_once('ticket/ticket_functions.php');
require_once('forms/forms_functions.php');
require_once('templates/template_functions.php');
require_once('fields/field_functions.php');
require_once('piping/piping_functions.php');
require_once('leads/leads_functions.php');
require_once('notifications/notification_functions.php');
require_once('faq/faq_functions.php');